# Generated by Django 4.2.7 on 2025-10-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("birds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("medication", "Medication"),
                            ("treatment", "Treatment"),
                            ("inspection", "Health Inspection"),
                            ("disease_outbreak", "Disease Outbreak"),
                            ("mortality", "Mortality Record"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="birds.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_health_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Record",
                "verbose_name_plural": "Health Records",
                "db_table": "health_records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                ("batch_number", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=100)),
                ("administration_method", models.CharField(max_length=100)),
                ("birds_vaccinated", models.PositiveIntegerField()),
                ("next_vaccination_date", models.DateField(blank=True, null=True)),
                (
                    "health_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_details",
                        to="health.healthrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination",
                "verbose_name_plural": "Vaccinations",
                "db_table": "vaccinations",
            },
        ),
        migrations.CreateModel(
            name="MortalityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField()),
                (
                    "cause_category",
                    models.CharField(
                        choices=[
                            ("disease", "Disease"),
                            ("accident", "Accident"),
                            ("predator", "Predator"),
                            ("heat_stress", "Heat Stress"),
                            ("cold_stress", "Cold Stress"),
                            ("unknown", "Unknown"),
                            ("culling", "Culling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specific_cause",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("age_at_death", models.PositiveIntegerField(help_text="Age in days")),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_records",
                        to="birds.batch",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_mortalities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mortality Record",
                "verbose_name_plural": "Mortality Records",
                "db_table": "mortality_records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                ("administration_method", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField()),
                (
                    "withdrawal_period",
                    models.PositiveIntegerField(help_text="Withdrawal period in days"),
                ),
                ("birds_treated", models.PositiveIntegerField()),
                (
                    "health_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_details",
                        to="health.healthrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "db_table": "medications",
            },
        ),
    ]
