# Generated by Django 5.1.4 on 2026-02-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('users', '0005_user_email_verification_code_user_last_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalityrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='users.organization'),
        ),
    ]
