# Generated by Django 4.2.7 on 2025-09-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_batch_status'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='flock',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='flocks.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='flocks.batch'),
            preserve_default=False,
        ),
    ]
