# Generated by Django 4.2.7 on 2025-10-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_remove_flock_breed_remove_flock_created_by_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eggproduction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='batch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='birds.batch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eggproduction',
            unique_together={('batch', 'date')},
        ),
        migrations.RemoveField(
            model_name='eggproduction',
            name='flock',
        ),
    ]
