# Generated by Django 4.2.7 on 2025-09-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
        ('flocks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_weights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentalrecord',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_records', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='environmentalrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_environmental', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_egg_productions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eggproduction',
            unique_together={('flock', 'date')},
        ),
    ]
