# Generated by Django 5.1.4 on 2026-02-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_eggproduction_unique_together_and_more'),
        ('users', '0005_user_email_verification_code_user_last_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggproduction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='environmentalrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_records', to='users.organization'),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='users.organization'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='users.organization'),
        ),
    ]
