version: '3.8'

services:
  # db:
  #   image: docker.io/library/postgres:15
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: docker.io/library/redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    entrypoint: ["/bin/bash","/code/docker/django/entrypoint.sh"]
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - STATIC_ROOT=/tmp/staticfiles
      - LOGS_DIR=/tmp/minija-logs
    volumes:
      - .:/code
      - staticfiles:/tmp/staticfiles
      - minija_logs:/tmp/minija-logs
    network_mode: host
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    environment:
      - VITE_API_URL=http://django:8000/api
    depends_on:
      - django
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
  staticfiles:
  minija_logs:
