# Generated by Django 5.1.4 on 2026-02-08 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0002_delete_historicalentry'),
        ('users', '0005_user_email_verification_code_user_last_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_kg', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('birds_count', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_entries', to='users.organization')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
