# Generated by Django 4.2.7 on 2025-09-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species', models.CharField(default='Chicken', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('average_weight', models.DecimalField(decimal_places=2, help_text='Average weight in kg', max_digits=6)),
                ('egg_production_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Eggs per year', max_digits=5, null=True)),
                ('maturity_age', models.PositiveIntegerField(help_text='Maturity age in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_id', models.CharField(max_length=50, unique=True)),
                ('flock_type', models.CharField(choices=[('broiler', 'Broiler'), ('layer', 'Layer'), ('breeder', 'Breeder'), ('pullet', 'Pullet')], max_length=20)),
                ('initial_count', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField()),
                ('hatch_date', models.DateField()),
                ('source', models.CharField(help_text='Hatchery or supplier', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('processed', 'Processed'), ('deceased', 'Deceased'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flock',
                'verbose_name_plural': 'Flocks',
                'db_table': 'flocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('transfer', 'Transfer'), ('sale', 'Sale'), ('processing', 'Processing'), ('mortality', 'Mortality'), ('culling', 'Culling')], max_length=20)),
                ('bird_count', models.PositiveIntegerField()),
                ('movement_date', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='flocks.flock')),
                ('from_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='farms.building')),
            ],
            options={
                'verbose_name': 'Flock Movement',
                'verbose_name_plural': 'Flock Movements',
                'db_table': 'flock_movements',
                'ordering': ['-movement_date'],
            },
        ),
    ]
