# Generated by Django 4.2.7 on 2025-09-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0003_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold')], default='active', max_length=20),
        ),
    ]
