# Generated by Django 4.2.7 on 2025-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('user', 'System User')], default='user', max_length=20),
        ),
    ]
