# Generated by Django 4.2.7 on 2025-10-20 16:02

from django.db import migrations, models
import uuid


def gen_unique_ids(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        # Generate a unique value (e.g., UUID or based on other fields)
        row.email_verification_token = uuid.uuid4().hex
        row.save(update_fields=["email_verification_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(gen_unique_ids, reverse_code=migrations.RunPython.noop),
    ]
