# Generated by Django 4.2.7 on 2025-10-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flock',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flockmovement',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='flockmovement',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
