# Generated by Django 4.2.7 on 2025-09-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0002_initial'),
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flockmovement',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flockmovement',
            name='to_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='farms.building'),
        ),
        migrations.AddField(
            model_name='flock',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='flocks.breed'),
        ),
        migrations.AddField(
            model_name='flock',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='farms.building'),
        ),
        migrations.AddField(
            model_name='flock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flock',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='farms.farm'),
        ),
    ]
