# Generated by Django 4.2.7 on 2025-09-28 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('supplier', models.CharField(max_length=100)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('initial_count', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'db_table': 'batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
