# Generated by Django 5.1.4 on 2026-02-07 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_delete_flock_delete_flockmovement'),
        ('users', '0005_user_email_verification_code_user_last_otp_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'status'], name='batches_organiz_5e2140_idx'),
        ),
    ]
