# Generated by Django 4.2.7 on 2025-10-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('established_date', models.DateField()),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_farms', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'db_table': 'farms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building_type', models.CharField(choices=[('broiler_house', 'Broiler House'), ('layer_house', 'Layer House'), ('breeder_house', 'Breeder House'), ('nursery', 'Nursery'), ('feed_storage', 'Feed Storage'), ('equipment_storage', 'Equipment Storage'), ('office', 'Office'), ('other', 'Other')], max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of birds')),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in meters', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in meters', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in meters', max_digits=8)),
                ('construction_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'buildings',
                'unique_together': {('farm', 'name')},
            },
        ),
    ]
