# Generated by Django 4.2.7 on 2025-09-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='farms.farm'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('farm', 'name')},
        ),
    ]
