# Generated by Django 5.1.4 on 2026-02-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_alert_flock_remove_report_flocks_alert_batch_and_more'),
        ('users', '0005_user_email_verification_code_user_last_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.organization'),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.organization'),
        ),
    ]
