name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint and enforce score threshold
      run: |
        set -euo pipefail
        # Gather Python files tracked by git, excluding any inside migrations/ directories
        FILES=$(git ls-files '*.py' | grep -v '/migrations/' || true)
        if [ -z "${FILES}" ]; then
          echo "No Python files to lint (all files excluded or none tracked)."
          exit 0
        fi
        echo "Running pylint on the following files:"
        echo "${FILES}"

        # Run pylint and enforce a minimum overall score of 8.0. pylint exits non-zero if below threshold.
        pylint ${FILES} --fail-under=8.0
